package com.guest_platform;

import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.math.BigDecimal; import java.time.*; import java.util.Arrays; import java.util.UUID;
import jakarta.servlet.http.Cookie;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc;
import com.guest_platform.dto.*; import com.guest_platform.entity.*; import com.guest_platform.exception.LifecycleConflictException; import com.guest_platform.repository.*; import com.guest_platform.service.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class HostLifecycleIntegrationTest {
 @Autowired HostRepository hosts; @Autowired AdminUserRepository admins; @Autowired HostVerificationRepository verifications;
 @Autowired HostVerificationEventRepository events; @Autowired HostAgreementVersionRepository agreements; @Autowired HostAgreementAcceptanceRepository acceptances;
 @Autowired PropertyRepository properties; @Autowired HostPayoutSettingsRepository payouts; @Autowired AdminAuditLogRepository auditRows;
 @Autowired HostVerificationService verification; @Autowired HostAgreementService agreement; @Autowired HostOnboardingService onboarding;
 @Autowired HostIdentityFingerprintService fingerprints; @Autowired HostSessionService sessions; @Autowired PasswordEncoder encoder; @Autowired MockMvc mockMvc;

 @Test void newHostIsUnverifiedAndCanSubmitWithoutExposingRawId(){Host h=host();assertThat(verification.getForHost(h.getId()).status()).isEqualTo(HostVerificationStatus.UNVERIFIED);String raw="12345678";HostVerificationResponse response=verification.submit(h.getId(),request(raw));assertThat(response.status()).isEqualTo(HostVerificationStatus.SUBMITTED);assertThat(response.idNumberLast4()).isEqualTo("5678");assertThat(response.phone()).isEqualTo("+254712345678");assertThat(Arrays.stream(HostVerificationResponse.class.getRecordComponents()).map(component->component.getName()).toList()).contains("idNumberLast4","phone").doesNotContain("idNumber","rawId","fullId","idFingerprint","fingerprint");HostVerification stored=verifications.findByHostId(h.getId()).orElseThrow();assertThat(stored.getIdFingerprint()).isNotEqualTo(raw).isEqualTo(fingerprints.fingerprint(HostIdentityType.NATIONAL_ID,raw));}
 @Test void kenyanPassportSucceedsAndRemainsSubmitted(){Host h=host();HostVerificationResponse response=verification.submit(h.getId(),verificationRequest(HostIdentityType.PASSPORT,"A 12-34/56","0712345678","KE"));assertThat(response.status()).isEqualTo(HostVerificationStatus.SUBMITTED);assertThat(response.idType()).isEqualTo(HostIdentityType.PASSPORT);assertThat(response.idNumberLast4()).isEqualTo("3456");assertThat(response.phone()).isEqualTo("+254712345678");assertThat(response.countryCode()).isEqualTo("KE");}
 @Test void congolesePassportUsesE164PhoneAndNeverPersistsOrReturnsRawNumber(){Host h=host();String raw="OP 12-34/56";HostVerificationResponse response=verification.submit(h.getId(),verificationRequest(HostIdentityType.PASSPORT,raw,"+243812345678","cd"));assertThat(response.status()).isEqualTo(HostVerificationStatus.SUBMITTED);assertThat(response.idNumberLast4()).isEqualTo("3456");assertThat(response.phone()).isEqualTo("+243812345678");assertThat(response.countryCode()).isEqualTo("CD");assertThat(Arrays.stream(HostVerificationResponse.class.getRecordComponents()).map(component->component.getName()).toList()).doesNotContain("idNumber","rawId","fullId","idFingerprint","fingerprint");HostVerification stored=verifications.findByHostId(h.getId()).orElseThrow();assertThat(Arrays.stream(HostVerification.class.getDeclaredFields()).map(field->field.getName()).toList()).doesNotContain("idNumber","rawId","fullId");assertThat(stored.getIdNumberLast4()).isEqualTo("3456");assertThat(stored.getIdFingerprint()).isNotEqualTo(raw).isEqualTo(fingerprints.fingerprint(HostIdentityType.PASSPORT,"OP123456"));}
 @Test void documentAndPhoneCountriesAreIndependent(){assertSubmittedPhone("CD",HostIdentityType.PASSPORT,"OP123456","+243812345678");assertSubmittedPhone("CD",HostIdentityType.PASSPORT,"OP123457","+254712345678");assertSubmittedPhone("KE",HostIdentityType.PASSPORT,"OP123458","+243812345678");assertSubmittedPhone("KE",HostIdentityType.PASSPORT,"OP123459","+254712345678");assertSubmittedPhone("KE",HostIdentityType.NATIONAL_ID,"12345678","+254712345678");assertSubmittedPhone("KE",HostIdentityType.NATIONAL_ID,"12345679","+243812345678");}
 @Test void congoleseNationalIdMalformedPhonesAndUnsupportedCallingCodesAreRejected(){assertThatThrownBy(()->verification.submit(host().getId(),verificationRequest(HostIdentityType.NATIONAL_ID,"12345678","+243812345678","CD"))).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("NATIONAL_ID").hasMessageContaining("CD");assertThatThrownBy(()->verification.submit(host().getId(),verificationRequest(HostIdentityType.PASSPORT,"OP123456","0812345678","CD"))).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("E.164");assertThatThrownBy(()->verification.submit(host().getId(),verificationRequest(HostIdentityType.PASSPORT,"OP123456","+255712345678","CD"))).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("not supported");assertThatThrownBy(()->verification.submit(host().getId(),verificationRequest(HostIdentityType.NATIONAL_ID,"12345678","+254812345678","KE"))).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("not supported");}
 @Test void fingerprintIsDeterministicProtectedAndDedicated(){assertThat(fingerprints.fingerprint(HostIdentityType.NATIONAL_ID,"12 345-678")).isEqualTo(fingerprints.fingerprint(HostIdentityType.NATIONAL_ID,"12345678")).hasSize(64).doesNotContain("12345678");}
 @Test void reviewApproveRejectResubmitAndInvalidTransitionsAreEnforced(){Host approvedHost=host();verification.submit(approvedHost.getId(),request("22345678"));AdminUser operations=admin(AdminRole.OPERATIONS);assertThat(verification.startReview(operations.getId(),approvedHost.getId()).status()).isEqualTo(HostVerificationStatus.UNDER_REVIEW);assertThat(verification.approve(operations.getId(),approvedHost.getId()).status()).isEqualTo(HostVerificationStatus.VERIFIED);assertThatThrownBy(()->verification.submit(approvedHost.getId(),request("32345678"))).isInstanceOf(LifecycleConflictException.class).extracting("code").isEqualTo("HOST_VERIFICATION_ALREADY_VERIFIED");
  Host rejectedHost=host();verification.submit(rejectedHost.getId(),request("42345678"));verification.startReview(operations.getId(),rejectedHost.getId());verification.reject(operations.getId(),rejectedHost.getId(),"Document could not be confirmed");assertThat(verification.submit(rejectedHost.getId(),request("52345678")).status()).isEqualTo(HostVerificationStatus.SUBMITTED);assertThatThrownBy(()->verification.approve(operations.getId(),rejectedHost.getId())).isInstanceOf(LifecycleConflictException.class);}
 @Test void supportIsReadOnlyWhileOperationsCanReview(){Host h=host();verification.submit(h.getId(),request("62345678"));AdminUser support=admin(AdminRole.SUPPORT);assertThatThrownBy(()->verification.startReview(support.getId(),h.getId())).isInstanceOf(AccessDeniedException.class);AdminUser operations=admin(AdminRole.OPERATIONS);assertThat(verification.startReview(operations.getId(),h.getId()).status()).isEqualTo(HostVerificationStatus.UNDER_REVIEW);}
 @Test void suspensionIsSeparateAndReactivationPreservesVerification(){Host h=host();AdminUser operations=admin(AdminRole.OPERATIONS);AdminUser superAdmin=admin(AdminRole.SUPER_ADMIN);verification.submit(h.getId(),request("72345678"));verification.startReview(operations.getId(),h.getId());verification.approve(operations.getId(),h.getId());AdminHostVerificationResponse suspended=verification.suspend(superAdmin.getId(),h.getId(),"Compliance review");assertThat(suspended.accountStatus()).isEqualTo(HostAccountStatus.SUSPENDED);assertThat(suspended.status()).isEqualTo(HostVerificationStatus.VERIFIED);assertThatThrownBy(()->verification.submit(h.getId(),request("82345678"))).isInstanceOf(LifecycleConflictException.class).extracting("code").isEqualTo("HOST_ACCOUNT_SUSPENDED");AdminHostVerificationResponse active=verification.reactivate(superAdmin.getId(),h.getId());assertThat(active.accountStatus()).isEqualTo(HostAccountStatus.ACTIVE);assertThat(active.status()).isEqualTo(HostVerificationStatus.VERIFIED);}
 @Test void normalHostSessionCannotCallAdminEndpoints() throws Exception {Host h=host();String token=sessions.create(h).value();mockMvc.perform(get("/api/admin/verifications").cookie(new Cookie("HOSTVERO_SESSION",token))).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.code").value("ADMIN_AUTH_REQUIRED"));}
 @Test void superAdminCreatesImmutableVersionsAndActivationSelectsOneCurrent(){AdminUser superAdmin=admin(AdminRole.SUPER_ADMIN);AgreementResponse first=agreement.create(superAdmin.getId(),agreementRequest("v-"+UUID.randomUUID(),true));assertThat(first.active()).isTrue();assertThat(first.content()).isEqualTo("Durable legal terms");assertThatThrownBy(()->agreement.create(superAdmin.getId(),new AdminAgreementCreateRequest(first.version(),"Changed","Changed text",Instant.now(),true,false))).isInstanceOf(LifecycleConflictException.class);AgreementResponse second=agreement.create(superAdmin.getId(),agreementRequest("v-"+UUID.randomUUID(),false));agreement.activate(superAdmin.getId(),second.id());assertThat(agreement.currentVersionOrNull()).isEqualTo(second.version());assertThat(agreements.findById(first.id()).orElseThrow().isActive()).isFalse();}
 @Test void nonSuperAdminCannotCreateOrActivateAgreement(){AdminUser operations=admin(AdminRole.OPERATIONS);assertThatThrownBy(()->agreement.create(operations.getId(),agreementRequest("v-"+UUID.randomUUID(),true))).isInstanceOf(AccessDeniedException.class);}
 @Test void hostReadsAcceptsIdempotentlyAndRejectsStaleVersion(){AdminUser superAdmin=admin(AdminRole.SUPER_ADMIN);Host h=host();AgreementResponse current=agreement.create(superAdmin.getId(),agreementRequest("v-"+UUID.randomUUID(),true));assertThat(agreement.current(h.getId()).accepted()).isFalse();AgreementResponse accepted=agreement.accept(h.getId(),new AgreementAcceptanceRequest(current.version()),"198.51.100.7","Browser\nSecret");AgreementResponse repeated=agreement.accept(h.getId(),new AgreementAcceptanceRequest(current.version()),"198.51.100.8","Other");assertThat(repeated.acceptedAt()).isEqualTo(accepted.acceptedAt());HostAgreementAcceptance row=acceptances.findByHostIdAndAgreementVersionId(h.getId(),current.id()).orElseThrow();assertThat(row.getEventType()).isEqualTo("HOST_AGREEMENT_ACCEPTED");assertThat(row.getIpAddressHash()).hasSize(64).doesNotContain("198.51.100.7");assertThat(row.getUserAgentSummary()).isNull();assertThatThrownBy(()->agreement.accept(h.getId(),new AgreementAcceptanceRequest("stale"),"198.51.100.7",null)).isInstanceOf(LifecycleConflictException.class).extracting("code").isEqualTo("HOST_AGREEMENT_STALE_VERSION");}
 @Test void readinessIsDerivedAndTrueOnlyWhenEveryRequirementIsComplete(){Host h=host();AdminUser operations=admin(AdminRole.OPERATIONS);AdminUser superAdmin=admin(AdminRole.SUPER_ADMIN);AgreementResponse current=agreement.create(superAdmin.getId(),agreementRequest("v-"+UUID.randomUUID(),true));assertThat(onboarding.get(h.getId()).ready()).isFalse();verification.submit(h.getId(),request("92345678"));verification.startReview(operations.getId(),h.getId());verification.approve(operations.getId(),h.getId());agreement.accept(h.getId(),new AgreementAcceptanceRequest(current.version()),"203.0.113.1","Test");Property property=new Property(h);property.update("Test property",PropertyType.APARTMENT,"Nairobi","https://maps.example",2,new BigDecimal("1000"),"KES",LocalTime.of(14,0),LocalTime.of(10,0),null,null,null,null,"+254700000000",true,null,null,null,null,null);properties.save(property);payouts.save(new HostPayoutSettings(h,PayoutMethod.BANK_ACCOUNT,"001","1234","Host", "SUB_"+UUID.randomUUID(),null,null,null));HostOnboardingResponse ready=onboarding.get(h.getId());assertThat(ready.verification().complete()).isTrue();assertThat(ready.agreement().complete()).isTrue();assertThat(ready.property().complete()).isTrue();assertThat(ready.payout().complete()).isTrue();assertThat(ready.ready()).isTrue();}
 @Test void lifecycleAuditAndHistoryContainNoRawIdentityOrSecrets(){Host h=host();AdminUser operations=admin(AdminRole.OPERATIONS);String raw="10345678";verification.submit(h.getId(),request(raw));verification.startReview(operations.getId(),h.getId());verification.reject(operations.getId(),h.getId(),"Photo mismatch");assertThat(events.findAll()).allSatisfy(e->{assertThat(e.getEventType()).doesNotContain(raw);if(e.getReason()!=null)assertThat(e.getReason()).doesNotContain(raw);});assertThat(auditRows.findAllByOrderByCreatedAtAsc()).allSatisfy(a->{assertThat(a.getAction()).doesNotContain(raw);if(a.getReason()!=null)assertThat(a.getReason()).doesNotContain(raw);assertThat(a.getMetadataJson()).isNull();});}

 private Host host(){String key=UUID.randomUUID().toString();return hosts.saveAndFlush(new Host("host-"+key+"@example.com",encoder.encode("StrongPass!123"),"Test Host","+254700000000"));}
 private AdminUser admin(AdminRole role){String key=UUID.randomUUID().toString();return admins.saveAndFlush(new AdminUser("admin-"+key+"@example.com",encoder.encode("StrongPass!123"),role.name(),role));}
 private HostVerificationSubmissionRequest request(String id){return new HostVerificationSubmissionRequest("Legal Host",HostVerificationType.INDIVIDUAL,HostIdentityType.NATIONAL_ID,id,"0712345678","KE");}
 private HostVerificationSubmissionRequest verificationRequest(HostIdentityType idType,String id,String phone,String country){return new HostVerificationSubmissionRequest("Legal Host",HostVerificationType.INDIVIDUAL,idType,id,phone,country);}
 private void assertSubmittedPhone(String documentCountry,HostIdentityType idType,String id,String phone){HostVerificationResponse response=verification.submit(host().getId(),verificationRequest(idType,id,phone,documentCountry));assertThat(response.status()).isEqualTo(HostVerificationStatus.SUBMITTED);assertThat(response.countryCode()).isEqualTo(documentCountry);assertThat(response.phone()).isEqualTo(phone);}
 private AdminAgreementCreateRequest agreementRequest(String version,boolean active){return new AdminAgreementCreateRequest(version,"Host Agreement","Durable legal terms",Instant.now(),true,active);}
}
