package com.guest_platform.service;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Instant; import java.util.*;
import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.guest_platform.dto.*; import com.guest_platform.entity.*; import com.guest_platform.exception.*; import com.guest_platform.repository.*;
@Service
public class HostAgreementService {
 private final HostAgreementVersionRepository versions; private final HostAgreementAcceptanceRepository acceptances; private final HostRepository hosts; private final AdminUserRepository admins; private final AdminAuditService audit; private final HostIdentityFingerprintService fingerprints;
 public HostAgreementService(HostAgreementVersionRepository versions,HostAgreementAcceptanceRepository acceptances,HostRepository hosts,AdminUserRepository admins,AdminAuditService audit,HostIdentityFingerprintService fingerprints){this.versions=versions;this.acceptances=acceptances;this.hosts=hosts;this.admins=admins;this.audit=audit;this.fingerprints=fingerprints;}
 @Transactional(readOnly=true) public AgreementResponse current(UUID hostId){HostAgreementVersion version=currentVersion();HostAgreementAcceptance acceptance=acceptances.findByHostIdAndAgreementVersionId(hostId,version.getId()).orElse(null);return AgreementResponse.of(version,acceptance!=null,acceptance==null?null:acceptance.getAcceptedAt());}
 @Transactional public AgreementResponse accept(UUID hostId,AgreementAcceptanceRequest request,String ip,String userAgent){Host host=hosts.findById(hostId).orElseThrow(()->new LifecycleNotFoundException("HOST_AGREEMENT_NOT_AVAILABLE","Host was not found."));HostAgreementVersion current=currentVersion();if(!current.getVersion().equals(request.version().trim()))throw new LifecycleConflictException("HOST_AGREEMENT_STALE_VERSION","The agreement version is no longer current.");HostAgreementAcceptance existing=acceptances.findByHostIdAndAgreementVersionId(hostId,current.getId()).orElse(null);if(existing!=null)return AgreementResponse.of(current,true,existing.getAcceptedAt());String ipHash=fingerprints.privacyHash("AGREEMENT_IP",ip);HostAgreementAcceptance created=acceptances.save(new HostAgreementAcceptance(host,current,ipHash,null));return AgreementResponse.of(current,true,created.getAcceptedAt());}
 @Transactional public AgreementResponse create(UUID adminId,AdminAgreementCreateRequest request){AdminUser admin=admin(adminId);requireSuper(admin);String version=request.version().trim();if(versions.findByVersion(version).isPresent())throw new LifecycleConflictException("HOST_AGREEMENT_ALREADY_EXISTS","Agreement versions are immutable; create a new version.");String content=request.content().trim();HostAgreementVersion entity=versions.saveAndFlush(new HostAgreementVersion(version,request.title().trim(),content,sha256(content),request.effectiveAt(),request.materialChange(),request.activate(),admin));if(request.activate())versions.deactivateOthers(entity.getId());audit.record(admin,AdminAuditService.HOST_AGREEMENT_CREATED,"HOST_AGREEMENT",entity.getId().toString(),null);if(request.activate())audit.record(admin,AdminAuditService.HOST_AGREEMENT_ACTIVATED,"HOST_AGREEMENT",entity.getId().toString(),null);return AgreementResponse.of(entity,false,null);}
 @Transactional public AgreementResponse activate(UUID adminId,UUID agreementId){AdminUser admin=admin(adminId);requireSuper(admin);HostAgreementVersion entity=versions.findById(agreementId).orElseThrow(()->new LifecycleNotFoundException("HOST_AGREEMENT_NOT_AVAILABLE","Agreement version was not found."));versions.deactivateOthers(entity.getId());entity.activate();audit.record(admin,AdminAuditService.HOST_AGREEMENT_ACTIVATED,"HOST_AGREEMENT",entity.getId().toString(),null);return AgreementResponse.of(entity,false,null);}
 @Transactional(readOnly=true) public List<AgreementResponse> list(){return versions.findAllByOrderByCreatedAtDesc().stream().map(v->AgreementResponse.of(v,false,null)).toList();}
 @Transactional(readOnly=true) public AgreementResponse get(UUID id){return AgreementResponse.of(versions.findById(id).orElseThrow(()->new LifecycleNotFoundException("HOST_AGREEMENT_NOT_AVAILABLE","Agreement version was not found.")),false,null);}
 @Transactional(readOnly=true) public boolean acceptedCurrent(UUID hostId){return versions.findFirstByActiveTrueOrderByEffectiveAtDesc().map(v->acceptances.existsByHostIdAndAgreementVersionId(hostId,v.getId())).orElse(false);}
 @Transactional(readOnly=true) public String currentVersionOrNull(){return versions.findFirstByActiveTrueOrderByEffectiveAtDesc().map(HostAgreementVersion::getVersion).orElse(null);}
 private HostAgreementVersion currentVersion(){return versions.findFirstByActiveTrueOrderByEffectiveAtDesc().orElseThrow(()->new LifecycleNotFoundException("HOST_AGREEMENT_NOT_AVAILABLE","No active host agreement is available."));}
 private AdminUser admin(UUID id){return admins.findById(id).orElseThrow(()->new AccessDeniedException("Admin not found"));} private void requireSuper(AdminUser a){if(a.getRole()!=AdminRole.SUPER_ADMIN)throw new AccessDeniedException("Admin role is not permitted");}
 private String sha256(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("Agreement hashing is unavailable",e);}}
}
