package com.guest_platform.service;

import java.time.Instant; import java.util.*; import java.util.regex.Pattern; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.guest_platform.dto.*; import com.guest_platform.entity.*; import com.guest_platform.exception.*; import com.guest_platform.repository.*;

@Service
public class HostVerificationService {
 // TODO Phase 11: add encrypted private-object document storage with short-lived, admin-authorized access.
 public static final String HOST_VERIFICATION_SUBMITTED="HOST_VERIFICATION_SUBMITTED";
 private static final Pattern ISO_ALPHA_2=Pattern.compile("[A-Z]{2}");
 private static final Pattern E164=Pattern.compile("\\+[1-9]\\d{7,14}");
 private static final Map<String,CountryRules> COUNTRY_RULES=Map.of(
  "KE",new CountryRules(Set.of(HostIdentityType.NATIONAL_ID,HostIdentityType.PASSPORT)),
  "CD",new CountryRules(Set.of(HostIdentityType.PASSPORT)));
 private static final Map<String,Pattern> PHONE_RULES=Map.of(
  "+254",Pattern.compile("[17]\\d{8}"),
  "+243",Pattern.compile("[1-9]\\d{8}"));
 private final HostRepository hosts; private final HostVerificationRepository verifications; private final HostVerificationEventRepository events; private final AdminUserRepository admins; private final AdminAuditService audit; private final HostIdentityFingerprintService fingerprints;
 public HostVerificationService(HostRepository hosts,HostVerificationRepository verifications,HostVerificationEventRepository events,AdminUserRepository admins,AdminAuditService audit,HostIdentityFingerprintService fingerprints){this.hosts=hosts;this.verifications=verifications;this.events=events;this.admins=admins;this.audit=audit;this.fingerprints=fingerprints;}

 @Transactional(readOnly=true) public HostVerificationResponse getForHost(UUID hostId){Host host=host(hostId);return verifications.findByHostId(hostId).map(v->HostVerificationResponse.from(v,host.getAccountStatus()==HostAccountStatus.SUSPENDED?host.getAccountSuspensionReason():null)).orElseGet(()->HostVerificationResponse.unverified(host));}
 @Transactional public HostVerificationResponse submit(UUID hostId,HostVerificationSubmissionRequest request){Host host=host(hostId);if(host.getAccountStatus()==HostAccountStatus.SUSPENDED)throw conflict("HOST_ACCOUNT_SUSPENDED","Suspended hosts cannot submit verification.");
  Normalized n=normalize(request); HostVerification existing=verifications.findForUpdateByHostId(hostId).orElse(null); HostVerificationStatus previous=existing==null?HostVerificationStatus.UNVERIFIED:existing.getStatus();
  if(existing==null){existing=new HostVerification(host,n.legalName,request.verificationType(),request.idType(),n.last4,n.fingerprint,n.phone,n.countryCode);verifications.save(existing);}
  else if(existing.getStatus()==HostVerificationStatus.REJECTED){existing.resubmit(n.legalName,request.verificationType(),request.idType(),n.last4,n.fingerprint,n.phone,n.countryCode);}
  else if(existing.getStatus()==HostVerificationStatus.VERIFIED)throw conflict("HOST_VERIFICATION_ALREADY_VERIFIED","Verified identity details cannot be overwritten.");
  else throw conflict("HOST_VERIFICATION_INVALID_STATE","Verification cannot be submitted in its current state.");
  events.save(new HostVerificationEvent(existing,"HOST",hostId,HOST_VERIFICATION_SUBMITTED,previous,HostVerificationStatus.SUBMITTED,null));return HostVerificationResponse.from(existing,null);
 }
 @Transactional(readOnly=true) public AdminHostVerificationResponse adminGet(UUID hostId){Host host=host(hostId);return AdminHostVerificationResponse.from(host,verifications.findByHostId(hostId).orElse(null));}
 @Transactional(readOnly=true) public List<AdminHostVerificationResponse> list(HostVerificationStatus status,Instant submittedFrom,Instant reviewedFrom,String search){String q=search==null?null:search.trim().toLowerCase(Locale.ROOT);return verifications.findAllByOrderBySubmittedAtDesc().stream().filter(v->status==null||v.getStatus()==status).filter(v->submittedFrom==null||(v.getSubmittedAt()!=null&&!v.getSubmittedAt().isBefore(submittedFrom))).filter(v->reviewedFrom==null||(v.getReviewedAt()!=null&&!v.getReviewedAt().isBefore(reviewedFrom))).filter(v->q==null||q.isBlank()||v.getHost().getEmail().toLowerCase(Locale.ROOT).contains(q)||v.getHost().getFullName().toLowerCase(Locale.ROOT).contains(q)).map(v->AdminHostVerificationResponse.from(v.getHost(),v)).toList();}
 @Transactional public AdminHostVerificationResponse startReview(UUID adminId,UUID hostId){AdminUser admin=admin(adminId);requireReviewRole(admin);return transition(admin,hostId,HostVerificationStatus.UNDER_REVIEW,null);}
 @Transactional public AdminHostVerificationResponse approve(UUID adminId,UUID hostId){AdminUser admin=admin(adminId);requireReviewRole(admin);return transition(admin,hostId,HostVerificationStatus.VERIFIED,null);}
 @Transactional public AdminHostVerificationResponse reject(UUID adminId,UUID hostId,String reason){AdminUser admin=admin(adminId);requireReviewRole(admin);return transition(admin,hostId,HostVerificationStatus.REJECTED,cleanReason(reason));}
 @Transactional public AdminHostVerificationResponse suspend(UUID adminId,UUID hostId,String reason){AdminUser admin=admin(adminId);requireSuper(admin);Host host=host(hostId);if(host.getAccountStatus()!=HostAccountStatus.ACTIVE)throw conflict("HOST_VERIFICATION_INVALID_STATE","Host account is not active.");String safe=cleanReason(reason);host.suspend(safe);audit.record(admin,AdminAuditService.HOST_SUSPENDED,"HOST",hostId.toString(),safe);return AdminHostVerificationResponse.from(host,verifications.findByHostId(hostId).orElse(null));}
 @Transactional public AdminHostVerificationResponse reactivate(UUID adminId,UUID hostId){AdminUser admin=admin(adminId);requireSuper(admin);Host host=host(hostId);if(host.getAccountStatus()!=HostAccountStatus.SUSPENDED)throw conflict("HOST_VERIFICATION_INVALID_STATE","Host account is not suspended.");host.reactivate();audit.record(admin,AdminAuditService.HOST_REACTIVATED,"HOST",hostId.toString(),null);return AdminHostVerificationResponse.from(host,verifications.findByHostId(hostId).orElse(null));}
 private AdminHostVerificationResponse transition(AdminUser admin,UUID hostId,HostVerificationStatus target,String reason){HostVerification v=verifications.findForUpdateByHostId(hostId).orElseThrow(()->new LifecycleNotFoundException("HOST_VERIFICATION_NOT_FOUND","Host verification was not found."));HostVerificationStatus previous=v.getStatus();try{if(target==HostVerificationStatus.UNDER_REVIEW)v.startReview(admin);else if(target==HostVerificationStatus.VERIFIED)v.approve(admin);else if(target==HostVerificationStatus.REJECTED)v.reject(admin,reason);else throw new IllegalStateException();}catch(IllegalStateException e){throw conflict("HOST_VERIFICATION_INVALID_STATE","The requested verification transition is not allowed.");}
  String action=target==HostVerificationStatus.UNDER_REVIEW?AdminAuditService.HOST_VERIFICATION_REVIEW_STARTED:target==HostVerificationStatus.VERIFIED?AdminAuditService.HOST_VERIFICATION_APPROVED:AdminAuditService.HOST_VERIFICATION_REJECTED;events.save(new HostVerificationEvent(v,"ADMIN",admin.getId(),action,previous,target,reason));audit.record(admin,action,"HOST_VERIFICATION",v.getId().toString(),reason);return AdminHostVerificationResponse.from(v.getHost(),v);}
 private Normalized normalize(HostVerificationSubmissionRequest r){String legal=r.legalName().trim().replaceAll("\\s+"," ");String country=r.countryCode().trim().toUpperCase(Locale.ROOT);if(!ISO_ALPHA_2.matcher(country).matches())throw new IllegalArgumentException("Country code must be an ISO alpha-2 code");CountryRules rules=COUNTRY_RULES.get(country);if(rules==null)throw new IllegalArgumentException("Verification is not currently supported for this country");if(!rules.idTypes().contains(r.idType()))throw new IllegalArgumentException(r.idType()+" is not currently supported for "+country);String id=r.idNumber().replaceAll("[\\s\\-_/]","").toUpperCase(Locale.ROOT);boolean valid=r.idType()==HostIdentityType.NATIONAL_ID?id.matches("\\d{6,12}"):id.matches("[A-Z0-9]{6,12}");if(!valid)throw new IllegalArgumentException("Identity number format is invalid");String phone=normalizePhone(r.phone());return new Normalized(legal,id.substring(Math.max(0,id.length()-4)),fingerprints.fingerprint(r.idType(),id),phone,country);}
 private String normalizePhone(String raw){String kenyan=raw.replaceAll("[\\s()-]","");if(kenyan.matches("0[17]\\d{8}"))return "+254"+kenyan.substring(1);if(kenyan.matches("254[17]\\d{8}"))return "+"+kenyan;if(kenyan.matches("\\+254[17]\\d{8}"))return kenyan;String phone=raw.trim();if(!E164.matcher(phone).matches())throw new IllegalArgumentException("Phone number must be a valid supported E.164 number");for(Map.Entry<String,Pattern> rule:PHONE_RULES.entrySet()){if(phone.startsWith(rule.getKey())&&rule.getValue().matcher(phone.substring(rule.getKey().length())).matches())return phone;}throw new IllegalArgumentException("Phone calling code or number format is not supported");}
 private Host host(UUID id){return hosts.findById(id).orElseThrow(()->new LifecycleNotFoundException("HOST_VERIFICATION_NOT_FOUND","Host was not found."));} private AdminUser admin(UUID id){return admins.findById(id).orElseThrow(()->new AccessDeniedException("Admin not found"));}
 private void requireReviewRole(AdminUser a){if(a.getRole()!=AdminRole.SUPER_ADMIN&&a.getRole()!=AdminRole.OPERATIONS)throw new AccessDeniedException("Admin role is not permitted");} private void requireSuper(AdminUser a){if(a.getRole()!=AdminRole.SUPER_ADMIN)throw new AccessDeniedException("Admin role is not permitted");}
 private String cleanReason(String r){if(r==null||r.isBlank())throw new IllegalArgumentException("Reason is required");return r.trim();} private LifecycleConflictException conflict(String code,String message){return new LifecycleConflictException(code,message);} private record CountryRules(Set<HostIdentityType> idTypes){} private record Normalized(String legalName,String last4,String fingerprint,String phone,String countryCode){}
}
